name: flutter_backgroud_app_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  #cupertino_icons
  cupertino_icons: ^1.0.8
  #flutter_background_service
  flutter_background_service: ^5.0.7
  #  flutter_background_service_ios: ^5.0.2
  #  flutter_background_service_android: ^6.2.4
  #flutter_local_notifications
  flutter_local_notifications: ^17.2.2
  #permission_handler
  permission_handler: ^11.3.1
  #shared_preferences
  shared_preferences: ^2.3.1
  #flutter_bloc
  flutter_bloc: ^8.1.6
  #equatable
  equatable: ^2.0.5
  #dio
  dio: ^5.5.0+1
  #get_it
  get_it: ^7.7.0
  #formz
  formz: ^0.7.0
  #dartz
  dartz: ^0.10.1
  #chuck_interceptor
  chuck_interceptor: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
