// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmekl3tD2-AL-bXEM-2fyjFpSlRvQPRXw',
    appId: '1:265689341748:web:e4bc3d359af31baeca0f61',
    messagingSenderId: '265689341748',
    projectId: 'flutter-background-f8e21',
    authDomain: 'flutter-background-f8e21.firebaseapp.com',
    storageBucket: 'flutter-background-f8e21.appspot.com',
    measurementId: 'G-G4DCETW6V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwkb_bHm6b2dBVqHwtbOe3_3fvcvl9GPo',
    appId: '1:265689341748:android:46334bf22b094250ca0f61',
    messagingSenderId: '265689341748',
    projectId: 'flutter-background-f8e21',
    storageBucket: 'flutter-background-f8e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF0KOYuNBjSgc5B4Fzgn9JCVymfeCF7Rk',
    appId: '1:265689341748:ios:27d85a696e9bfec0ca0f61',
    messagingSenderId: '265689341748',
    projectId: 'flutter-background-f8e21',
    storageBucket: 'flutter-background-f8e21.appspot.com',
    iosBundleId: 'com.example.flutterBackgroudAppExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF0KOYuNBjSgc5B4Fzgn9JCVymfeCF7Rk',
    appId: '1:265689341748:ios:27d85a696e9bfec0ca0f61',
    messagingSenderId: '265689341748',
    projectId: 'flutter-background-f8e21',
    storageBucket: 'flutter-background-f8e21.appspot.com',
    iosBundleId: 'com.example.flutterBackgroudAppExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmekl3tD2-AL-bXEM-2fyjFpSlRvQPRXw',
    appId: '1:265689341748:web:bc3d95c6d1ec7be8ca0f61',
    messagingSenderId: '265689341748',
    projectId: 'flutter-background-f8e21',
    authDomain: 'flutter-background-f8e21.firebaseapp.com',
    storageBucket: 'flutter-background-f8e21.appspot.com',
    measurementId: 'G-H6N1376CLK',
  );
}
